### ISSUE TITLE
请问如何分解不同QUIC实现的CPU占用？

### ISSUE THREAD

**Issue by Neoinvoker** [Winters123/QUIC-measurement-kit#5]
![1](https://github.com/Winters123/QUIC-measurement-kit/assets/133231780/e3771216-adb4-489d-9b38-07b4cd1b4501)
我在您的论文中看到这幅CPU占用分解图，我试图在lsquic上做类似的工作，希望将部分lsquic的CPU工作卸载到FPGA实现，请问您是如何实现统计不同模块（加解密 io等）的CPU占用的？

**Comment by Neoinvoker** [comment]
似乎是用Flamegraph实现的，我没有仔细看readme，打扰了

**Comment by Winters123** [comment]
没错，使用的flamegraph, 用perf进行性能测试 :)
